/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedElectriciansRouteImport } from './routes/_authenticated/electricians'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedSettlementRouteImport } from './routes/_authenticated/settlement'
import { Route as AuthenticatedElectricianLedgerRouteImport } from './routes/_authenticated/electrician/ledger'
import { Route as AuthenticatedElectricianRatesRouteImport } from './routes/_authenticated/electrician/rates'
import { Route as AuthenticatedLedgerElectricianIdRouteImport } from './routes/_authenticated/ledger/$electricianId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedElectriciansRoute =
  AuthenticatedElectriciansRouteImport.update({
    id: '/electricians',
    path: '/electricians',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettlementRoute = AuthenticatedSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedElectricianLedgerRoute =
  AuthenticatedElectricianLedgerRouteImport.update({
    id: '/electrician/ledger',
    path: '/electrician/ledger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedElectricianRatesRoute =
  AuthenticatedElectricianRatesRouteImport.update({
    id: '/electrician/rates',
    path: '/electrician/rates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLedgerElectricianIdRoute =
  AuthenticatedLedgerElectricianIdRouteImport.update({
    id: '/ledger/$electricianId',
    path: '/ledger/$electricianId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/electricians': typeof AuthenticatedElectriciansRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/settlement': typeof AuthenticatedSettlementRoute
  '/electrician/ledger': typeof AuthenticatedElectricianLedgerRoute
  '/electrician/rates': typeof AuthenticatedElectricianRatesRoute
  '/ledger/$electricianId': typeof AuthenticatedLedgerElectricianIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/electricians': typeof AuthenticatedElectriciansRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/settlement': typeof AuthenticatedSettlementRoute
  '/electrician/ledger': typeof AuthenticatedElectricianLedgerRoute
  '/electrician/rates': typeof AuthenticatedElectricianRatesRoute
  '/ledger/$electricianId': typeof AuthenticatedLedgerElectricianIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/electricians': typeof AuthenticatedElectriciansRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/settlement': typeof AuthenticatedSettlementRoute
  '/_authenticated/electrician/ledger': typeof AuthenticatedElectricianLedgerRoute
  '/_authenticated/electrician/rates': typeof AuthenticatedElectricianRatesRoute
  '/_authenticated/ledger/$electricianId': typeof AuthenticatedLedgerElectricianIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/electricians'
    | '/inventory'
    | '/settlement'
    | '/electrician/ledger'
    | '/electrician/rates'
    | '/ledger/$electricianId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/electricians'
    | '/inventory'
    | '/settlement'
    | '/electrician/ledger'
    | '/electrician/rates'
    | '/ledger/$electricianId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/electricians'
    | '/_authenticated/inventory'
    | '/_authenticated/settlement'
    | '/_authenticated/electrician/ledger'
    | '/_authenticated/electrician/rates'
    | '/_authenticated/ledger/$electricianId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/electricians': {
      id: '/_authenticated/electricians'
      path: '/electricians'
      fullPath: '/electricians'
      preLoaderRoute: typeof AuthenticatedElectriciansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settlement': {
      id: '/_authenticated/settlement'
      path: '/settlement'
      fullPath: '/settlement'
      preLoaderRoute: typeof AuthenticatedSettlementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/electrician/ledger': {
      id: '/_authenticated/electrician/ledger'
      path: '/electrician/ledger'
      fullPath: '/electrician/ledger'
      preLoaderRoute: typeof AuthenticatedElectricianLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/electrician/rates': {
      id: '/_authenticated/electrician/rates'
      path: '/electrician/rates'
      fullPath: '/electrician/rates'
      preLoaderRoute: typeof AuthenticatedElectricianRatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger/$electricianId': {
      id: '/_authenticated/ledger/$electricianId'
      path: '/ledger/$electricianId'
      fullPath: '/ledger/$electricianId'
      preLoaderRoute: typeof AuthenticatedLedgerElectricianIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedElectriciansRoute: typeof AuthenticatedElectriciansRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedSettlementRoute: typeof AuthenticatedSettlementRoute
  AuthenticatedElectricianLedgerRoute: typeof AuthenticatedElectricianLedgerRoute
  AuthenticatedElectricianRatesRoute: typeof AuthenticatedElectricianRatesRoute
  AuthenticatedLedgerElectricianIdRoute: typeof AuthenticatedLedgerElectricianIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedElectriciansRoute: AuthenticatedElectriciansRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedSettlementRoute: AuthenticatedSettlementRoute,
  AuthenticatedElectricianLedgerRoute: AuthenticatedElectricianLedgerRoute,
  AuthenticatedElectricianRatesRoute: AuthenticatedElectricianRatesRoute,
  AuthenticatedLedgerElectricianIdRoute: AuthenticatedLedgerElectricianIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
